{"name":"my_project",
 "type":"dir",
 "child":[{"name":"settings",
          "type":"dir",
          "child":[{"name":"__init__.py",
                    "type":"file"
                   },
                   {"name":"dev.py",
                    "type":"file"
                   },
                   {"name":"prod.py",
                    "type":"file"
                   }
                 ]
         },
         {"name":"mainapp",
          "type":"dir",
          "child":[{"name":"__init__.py",
                    "type":"file"
                   },
                   {"name":"models.py",
                    "type":"file"
                   },
                   {"name":"views.py",
                    "type":"file"
                   },
                   {"name":"views.py",
                    "type":"file"
                   },
                   {"name":"templates",
                    "type":"dir",
                    "child":[{"name":"mainapp",
                              "type":"dir",
                              "child":[{"name":"base.html",
                                        "type":"file"
                                       },
                                       {"name":"index.html",
                                        "type":"file"
                                       }
                                     ]
                              }
                            ]
                   }
                ]
         },
         {"name":"authapp",
          "type":"dir",
          "child":[{"name":"__init__.py",
                    "type":"file"
                   },
                   {"name":"models.py",
                    "type":"file"
                   },
                   {"name":"views.py",
                    "type":"file"
                   },
                   {"name":"templates",
                    "type":"dir",
                    "child":[{"name":"authapp",
                              "type":"dir",
                              "child":[{"name":"base.html",
                                        "type":"file"
                                       },
                                       {"name":"index.html",
                                        "type":"file"
                                       }
                                      ]
                             }
                            ]
                   }
                  ]
         }
        ]
}
